#ifndef NODE_STATISTICS_H
#define NODE_STATISTICS_H

/**
 * NodeStatistics - runtime statistics counters for a single Node instance.
 * Replaces 46 flat public + 9 private measurement-state members in node.h.
 * Array pointer members must be allocated externally (see InitializeVariables).
 */
struct NodeStatistics {

	// --- Packet / frame counters ---
	int    data_packets_sent;				///> Number of A-MPDUs (data transmissions) sent
	int    rts_cts_sent;					///> Number of RTS/CTS packets sent
	double num_packets_generated;			///> Number of packets generated by the AP
	double num_packets_dropped;				///> Number of packets dropped by the AP's buffer
	int    data_packets_acked;				///> Own A-MPDUs (data transmissions) that have been ACKed
	int    data_frames_acked;				///> Own individual MPDUs that have been ACKed (frames/packets = avg aggregation)
	int    data_packets_lost;				///> Own A-MPDUs that have been collided or lost
	int    rts_cts_lost;
	int    rts_lost_slotted_bo;				///> Number of RTS packets lost due to slotted BO
	int    num_tx_init_tried;				///> Number of TX initiations tried (whenever transmitter tries to access the channel)
	int    num_tx_init_not_possible;		///> Number of TX initiations not possible due to channel state and DCB model
	double prob_slotted_bo_collision;		///> Probability of slotted BO collision

	// --- Throughput / delay / utilization ---
	double throughput;						///> Throughput [Mbps]
	double throughput_loss;					///> Throughput of lost packets [Mbps]
	int    num_delay_measurements;			///> Number of delay measurements for averaging
	double sum_delays;						///> Sum of delays for averaging
	double average_delay;					///> Average delay from packet generation to ACK
	double average_rho;						///> Average rho metric (prob. of having packets in buffer and channel free)
	double average_utilization;				///> Average buffer utilization
	double generation_drop_ratio;			///> Probability of dropping a packet
	double average_waiting_time;			///> Average time between two channel accesses
	double bandwidth_used_txing;			///> Average bandwidth used for transmitting (RTS, CTS, ACK and DATA packets considered)

	// --- Backoff stats ---
	double expected_backoff;				///> Average computed BO value
	int    num_new_backoff_computations;	///> Number of backoff values computed (generated)

	// --- Channel idle tracking ---
	double sum_time_channel_idle;			///> Time the channel has been idle (no one transmits)
	double last_time_channel_is_idle;		///> Auxiliary: timestamp of the last idle start
	bool   channel_idle;					///> Whether the channel is currently idle

	// --- NAV tracking ---
	double last_time_not_in_nav;			///> Timestamp of the last time the node left NAV state
	double time_in_nav;						///> Total time spent in NAV state
	int    times_went_to_nav;				///> Number of times the node entered NAV state

	// --- MAPC / TXOP-sharing statistics ---
	int    num_icf_tx;                         ///> ICF frames sent (MAPC coordinator — one per TXOP initiated)
	int    num_icr_rx;                         ///> ICR frames received (MAPC coordinator)
	int    num_tf_tx;                          ///> TF frames sent (coordinator, Co-BF/Co-SR)
	int    num_mu_rts_tx;                      ///> MU-RTS frames sent (coordinator, Co-TDMA)
	int    num_icf_rx;                         ///> ICF frames received and accepted (coordinated AP)
	int    num_icr_tx;                         ///> ICR frames sent (coordinated AP)
	int    num_tf_rx;                          ///> TF frames received (coordinated AP, Co-BF/Co-SR)
	int    num_mu_rts_rx;                      ///> MU-RTS frames received (coordinated AP, Co-TDMA)
	double total_mapc_data_duration_own;       ///> Own DATA duration accumulated in MAPC TXOPs [s]
	double total_mapc_data_duration_shared;    ///> DATA duration allocated to peer APs by coordinator [s]
	double total_mapc_data_duration_allocated; ///> DATA duration allocated to this AP by coordinator [s]

	// --- Rolling-window (last-period) stats ---
	double last_measurements_window;
	double last_throughput;
	int    last_data_frames_acked;
	double last_average_delay;
	double last_sum_delays;
	int    last_num_delay_measurements;
	double last_sum_waiting_time;
	int    last_num_average_waiting_time_measurements;

	// --- Per-channel time arrays (allocated in InitializeVariables) ---
	double *total_time_transmitting_per_channel;		///> Time transmitting per channel
	double *total_time_transmitting_in_num_channels;	///> Time transmitting in N channels (ix 0: 1 ch, ix 1: 2 ch, ...)
	double *total_time_lost_per_channel;				///> Time transmitting per channel unsuccessfully
	double *total_time_lost_in_num_channels;			///> Time lost in N channels (ix 0: 1 ch, ix 1: 2 ch, ...) unsuccessfully
	double *total_time_channel_busy_per_channel;		///> Time the spectrum is occupied per channel
	double *last_total_time_transmitting_per_channel;
	double *last_total_time_lost_per_channel;

	// --- Per-transmission-width trial counters ---
	int    *num_trials_tx_per_num_channels;		///> Number of TX trials per number of channels
	int    *nacks_received;						///> Counter of the type of NACKs received

	// --- Per-STA arrays (allocated in InitializeVariables) ---
	double *throughput_per_sta;			///> Throughput assigned to each STA (Downlink mode)
	int    *data_packets_sent_per_sta;	///> Data packets sent to each STA (Downlink mode)
	int    *rts_cts_sent_per_sta;		///> RTS/CTS packets sent to each STA (Downlink mode)
	int    *data_packets_lost_per_sta;	///> Data packets lost for each STA (Downlink mode)
	int    *rts_cts_lost_per_sta;		///> RTS/CTS packets lost for each STA (Downlink mode)
	int    *data_packets_acked_per_sta;	///> Data packets acknowledged by each STA (Downlink mode)
	int    *data_frames_acked_per_sta;	///> Frames acknowledged by each STA (Downlink mode)

	// --- Rho / utilization measurement state (was private in node.h) ---
	int    flag_measure_rho;					///> Flag for activating rho measurement
	double delta_measure_rho;					///> Time [s] between two rho measurements
	int    num_measures_rho;					///> Number of measures to get the average rho metric
	int    num_measures_rho_accomplished;		///> Number of measures where rho condition is satisfied
	int    num_measures_utilization;			///> Number of measures for computing the utilization metric
	int    num_measures_buffer_with_packets;	///> Number of measures where the buffer had packets

	// --- Waiting-time measurement state (was private in node.h) ---
	double sum_waiting_time;					///> Sum of time waiting before transmitting
	double timestamp_new_trial_started;			///> Timestamp at which the current transmission trial started
	int    num_average_waiting_time_measurements; ///> Number of waiting-time measurements taken (for averaging)
};

#endif /* NODE_STATISTICS_H */
